- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/layouts/application.html.erb
EDITED FILES
- Application.html.erb (Google font headers)
- _fonts.scss
- _colors.scss
- _bootstrap_variables.scss
- pages/application.scss
> Core styling

- app/models/habit.rb
- app/models/log.rb
- app/models/relationship.rb
- app/models/user.rb
- Associations added
- Validations added
> Associations validations

- app/controllers/multistage_controller.rb
- app/views/multistage/_life_in_years_input.html.erb
- app/views/multistage/_life_in_years_output.html.erb
- app/views/multistage/_relationship_input.html.erb
- config/routes.rb
Initial steps added to Multifactor controller, route collections added, first 3 views added
all under multifactor files and titles
> Foundation for multifactor signin started

- app/controllers/multistage_controller.rb
- app/models/user.rb
FILES CHANGED
- multifactor controller
- user model validations
> Multifactor step-1 converts date and persists (with validation)

- app/controllers/multistages_controller.rb
- app/models/relationship.rb
- app/views/multistages/step3_input.html.erb
- config/routes.rb
FILES CHANGED
- multifactor controller
- step3_input view
- routes (step3_input/submit/output)
- relationship model (new collection for Day Month Year)
> Add step3 view form and foundation to multifactor controller step3

- app/assets/stylesheets/components/_habit_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_tracker.scss
- app/controllers/habits_controller.rb
- app/javascript/controllers/logs_container_scroll_controller.js
- app/views/habits/_habit_card.html.erb
- app/views/habits/show.html.erb
- app/views/habits/tracker.html.erb
- config/routes.rb
"Tracker" page now shows previous habit (as a line and circle as per design).
Need to add "current habit" button and future habits
> Habit container

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/habits_controller.rb
- app/models/habit.rb
- app/views/habits/index.html.erb
- app/views/habits/new.html.erb
- db/migrate/20240306190235_add_days_of_week_to_habits.rb
- db/migrate/20240306193341_remove_days_from_habits.rb
- db/schema.rb
- db/seeds.rb
Completed core styling including:
- Advanced checkboxes: days of the week in circles as per Figma design
> Habit form

- db/seeds.rb
contact_minutes_per_week has become contact_days and _per_peer
> updated seed file to match relationship-

- app/assets/stylesheets/components/_burger_menu.scss
- app/views/habits/index.html.erb
- app/views/shared/_burger_menu.html.erb
Styled the burger menu and added links
> Burger menu

- app/assets/stylesheets/pages/_multistage.scss
- app/controllers/multistages_controller.rb
- app/javascript/controllers/multistage_step1_controller.js
- app/javascript/controllers/multistage_step2_output_controller.js
- app/views/multistages/step2_output.html.erb
Added the Stimulus controller to handle all of the step2 outputs based on the provided step2 inputs.
> Multistage step2 output

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/buttons/_optional_button.scss
- app/javascript/controllers/signup_form_controller.js
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
RESPONSIVE SIGNUP FORM
- sign_up_form_controller.js heavy edits
- new button _class added
- new registration form for sign
> Sign up autofill

- app/controllers/multistages_controller.rb
- app/javascript/controllers/multistage_step2_controller.js
- app/javascript/controllers/multistage_step3_controller.js
- app/models/user.rb
- app/views/multistages/step3_input.html.erb
Implemented the full multistage step3 input process, including handling of the form, partial data validation, displaying errors and redirect to step3-output if successful. Data is added to session[:user_data]['step3'] to be used on the signup form. 
Next part of step3 will be building the output (including pie charts)
> Multistage step3 input

- app/assets/stylesheets/components/_header.scss
Added z-index of 8 to #header in _header scss partial. To make sure other items are below it on scrolling (z-index of side menu is 9 and of burger-menu icon is 10).
> Update of z-index of header element

- app/assets/stylesheets/pages/_multistage.scss
Made this change in order for the flex-column to start at the top of the page
> Added "justify-content: start" to the .container.step1 

- app/assets/stylesheets/components/habit_show_card.scss
- app/controllers/habits_controller.rb
- app/views/habits/new.html.erb
- app/views/shared/_habit_show_card.erb
- db/migrate/20240307202159_change_days_of_week_to_array_in_habits.rb
- db/schema.rb
[Got day selector working! Also fixed the image resolution on the habits
> Day select

- app/javascript/controllers/signup_form_controller.js
- app/views/devise/registrations/new.html.erb
FINAL OPERATIONAL FUNCTIONS BUILT FOR:
- signup_form_controller.js
- new.html.erb for the devise signup form
- user can be created
- button shows/hides the previous autofilled answers
LAST EDITS NEEDED
- Need to add validation redirection to avoid ruby errors displaying on the screen ("email already exists" for e.g.)
- Back button?
- redirects to the appropriate page (currently "home")
> signup form complete with showHide button logic for autofilled answers

- app/assets/stylesheets/components/buttons/_primary_button.scss
- app/javascript/controllers/signup_form_controller.js
- app/views/multistages/step2_output.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_burger_menu.html.erb
Aligned items on step2 pages center, added signup to burger when logged out, changes scss in primary-button to stop height skewing on certain pages
> minor styling and spacing changes

- app/javascript/controllers/multistage_step1_controller.js
- app/javascript/controllers/multistage_step2_output_controller.js
Added auto-scroll back to top for the coloring of the circles
> Multistage format updates

- Gemfile
- app/assets/stylesheets/components/_forms.scss
- app/views/habits/new.html.erb
- Also includes some habit form imporvements
> added chartkick gem file

- app/assets/stylesheets/components/_chip.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/habit_show_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/shared/_habit_show_card.erb
> Chip creation and habit card styling

- app/assets/stylesheets/components/_chip.scss
- app/assets/stylesheets/components/habit_show_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/models/habit.rb
- app/views/shared/_category_chip.html.erb
- app/views/shared/_habit_show_card.erb
Updated category colours so they're global and can be used for charts also. Also moved the category chips into  a partial in order to change the icons depending on the category chosen
> Category colours

- app/javascript/controllers/multistage_step1_controller.js
- app/views/multistages/_relationship_input.html.erb
- app/views/multistages/step3_input.html.erb
Fixes step1 back-button to not remove the date when going back (just resetting the animation)
> Updated back to previous section labels and fixed step1 back button 

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/controllers/user_profile_controller.js
- app/views/devise/registrations/edit.html.erb
- app/views/pages/user_profile.html.erb
- app/views/shared/_burger_menu.html.erb
can edit user details if current user on the profile page, adds "Profile" to burger when logged in
> User profile with links and edit functions

- app/controllers/habits_controller.rb
- app/views/habits/_habit_card.html.erb
- app/views/habits/tracker.html.erb
- Logic built so that future "logs" are automatically built on creation of habit
- Habits appear chronologically on Habit Tracker
> Sync habit tracker to current user

- app/controllers/habits_controller.rb
- app/views/habits/_habit_card.html.erb
- app/views/habits/_logs.html.erb
- app/views/habits/tracker.html.erb
- Logs now appear on Tracker for all Habits assigned to current user, in order of "time" set on creation
> Habit tracker

- app/controllers/habits_controller.rb
- app/models/log.rb
- app/views/pages/user_profile.html.erb
- db/seeds.rb
added attr-reader to logs model for easier use, methods built in controller to handle log iteration
> built method for log iteration on single habit based on complete

- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tracker_menu.scss
- app/assets/stylesheets/pages/_tracker.scss
- app/javascript/application.js
- app/javascript/controllers/tracker_dates_controller.js
- app/javascript/controllers/tracker_menu_controller.js
- app/views/habits/tracker.html.erb
- app/views/layouts/application.html.erb
WIP version of date selector, but requires intermediate merge to pick up the latest details on the logs
> Tracker date selector

- app/controllers/habits_controller.rb
- fixed issues with changes to "tracker" method
> fixed error in habit controller following merges

- app/assets/stylesheets/components/habit_show_card.scss
- app/controllers/habits_controller.rb
- app/views/habits/edit.html.erb
- app/views/habits/show.html.erb
- app/views/shared/_habit_show_card.erb
- config/routes.rb
"Completed edit and destroy functionality. Must consider the impact upon logs and habit tracking"
> Edit habit

- app/controllers/habits_controller.rb
FUNCTION
methods built to determine whether there is 1 or more habits, then iterates over the logs of each habit to determine the current streak
> streak determiner iteration built in controller

- app/assets/stylesheets/components/_habit_button_card.scss
- app/controllers/habits_controller.rb
- app/models/log.rb
- app/views/habits/_habit_first_card.html.erb
- app/views/habits/tracker.html.erb
- Function created so that when "logs" are made for each habit, it only appears based on the "weekly occurence" chosen by the user e.g. if "monday" and "every 3 weeks", it would show this coming Monday, and then every third Monday after that
> Log weekly occurrence function

- app/assets/stylesheets/components/_habit_card.scss
- app/javascript/controllers/tracker_menu_controller.js
- app/views/habits/_logs.html.erb
- app/views/habits/tracker.html.erb
Creating pull request to combine with latest formatting on tracker habit cards
> Tracker dates scroll interaction

- app/assets/stylesheets/components/_tracker_menu.scss
- app/javascript/controllers/tracker_menu_controller.js
- app/views/habits/tracker.html.erb
Updated year and month dropdown-menus to be able to select actual months/years and respective movements in the days menu
> Tracker menu dropdown functionality

- app/controllers/habits_controller.rb
Fixed habits_controller to update the current/best streaks with a new comparison method, reflected in the habit card partial
> Habit cards show correct current/best_streak, updates in DB

- app/controllers/application_controller.rb
- app/models/log.rb
- app/views/habits/_logs.html.erb
Updated animation for the tracker. Currently working again. 
Note: Also removed the Log completion attr_reader from the Log model. This was causing the issues with using the completed attribute for the logs
> Tracker completion animation fix

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tracker_side_menu.scss
- app/javascript/controllers/tracker_menu_controller.js
- app/views/habits/tracker.html.erb
Habits filtering to be implemented
> Tracker side menu

- app/javascript/controllers/tracker_menu_controller.js
Updated for when today is not in the current view of the menuDays (will use matchMenuScroll() method)
> Tracker goToToday fix

- app/javascript/controllers/tracker_menu_controller.js
Resolved issue of binding multiple event listener instances
> Tracker menu year dropdown fix

- app/assets/stylesheets/components/_habit_card.scss
- app/controllers/logs_controller.rb
- app/javascript/controllers/log_click_controller.js
- app/models/log.rb
- app/views/habits/_habit_first_card.html.erb
- app/views/habits/_logs.html.erb
- Seperated "format_message" method into two methods, handling "title" and the rest of the text on the habit card, to allow for different styling, size etc.
- Main text shows different message depending on past, 'today', future
- Card reminds user of 'trigger' if 'not completed' for 'today'
> Habit card

- app/javascript/controllers/log_click_controller.js
- app/views/habits/_logs.html.erb
Fixes the animation and date-menu issues
> Updated logs and click-controller

- app/assets/stylesheets/components/_habit_card.scss
- app/javascript/controllers/log_click_controller.js
- app/views/habits/_logs.html.erb
Also updated column distribution to 7-5 for the habit card
> Updated line split of the habit log card

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_habit_card.scss
- app/views/habits/new.html.erb
This applies to both tool-tips and for the encouragement message
> Added background blur to tooltip-back

- app/assets/stylesheets/components/_chip.scss
- app/assets/stylesheets/components/_habit_button_card.scss
- app/assets/stylesheets/components/_habit_card.scss
- app/controllers/logs_controller.rb
- app/models/log.rb
- app/views/habits/_habit_button_card.html.erb
- app/views/habits/_habit_first_card.html.erb
- app/views/habits/_logs.html.erb
- app/views/shared/_habit_show_card.erb
- added intro text to "first card" and removed circle
- added message to "final card" and replaced final circle with sun icon
- added chips to each card that pulls through "trigger" and "reward" for each habit the log is attached to
- changed text styling and positioning on habit cards
> First last habit card

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_habit_card.scss
- app/javascript/controllers/log_click_controller.js
- app/javascript/controllers/tracker_menu_controller.js
- app/views/habits/tracker.html.erb
- app/views/layouts/application.html.erb
Required clean-ups / fixes to align on latest branches merged. Currently tracker fully functional again
> Cleaned up various items to fix the issue with the side-menu

- app/assets/stylesheets/components/_forms.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> Sorted columns so that they look consistent with rest of app

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_logo.scss
- app/views/shared/_habit_show_card.erb
> Vertically centered the logo animation on encouragement message

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/shared/_habit_show_card.erb
Reduced dead space below nav bar on home page only and made the identity goal in the fhabit show card lower case
> More style tweaks

- app/assets/stylesheets/components/buttons/_tertiary_button.scss
- app/controllers/habits_controller.rb
- app/controllers/logs_controller.rb
- app/javascript/controllers/signup_form_controller.js
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/schema.rb
- db/seeds.rb
Lots of edits across files, tertiary-button edited, logs controller save method extended etc.
> Moved streak methods to appropriate controllers and rebuilt

- app/models/log.rb
- app/views/shared/_habit_show_card.erb
- db/seeds.rb
- "Habits" seeded
- Show page text altered slightly to improve appearance
> Pitch seed

- app/assets/stylesheets/components/_charts.scss
Have updated the text color for unavoidables in step3 of the multistage signup. Text colour slightly different vs the chart but I think it still works well. I did not want to change the chart color because I like the contrast / current looks
> Updated the chart legend color

- app/views/shared/_burger_menu.html.erb
Also moved testimonials up in the burger-menu positioning
> Updated reviews label to testimonials in burger menu

- config/routes.rb
added method to "routes" which defines root path based on sign-in
> fixed bug with redirecting after user sign in

- app/controllers/habits_controller.rb
- app/javascript/controllers/reviews_controller.js
- app/views/habits/_streak_container.html.erb
- app/views/reviews/_review_form.html.erb
- app/views/reviews/index.html.erb
- db/seeds.rb
Reviews changed to Success Stories, rowan review removed from seed, streak hardcoded for now, guards on streak method for new users
> changes to streaks reviews seed

- app/assets/stylesheets/components/_alert.scss
> flash-opaque

- app/views/shared/_burger_menu.html.erb
- db/seeds.rb
- added two testimonials
- changes burger menu to have 'success stories' instead of 'community'
> Testimonials seed

- app/views/devise/registrations/new.html.erb
> Added space beneath 'show previous answers
